import 'package:flutter/material.dart';
import '../utilities/product.dart';

final List<Product> allProducts = [ // Global list of all products available in the app
  // --- DONUTS ---
  Product(
    name: "Grimmace Grape",
    price: "4.80",
    color: const Color.fromARGB(255, 159, 40, 155),
    imagePath: "assets/images/donut1.jpg",
    category: "donut",
  ),
  Product(
    name: "Chocolate with Sprinkles",
    price: "4.50",
    color: const Color.fromRGBO(159, 121, 40, 1),
    imagePath: "assets/images/donut2.jpg",
    category: "donut",
  ),
  Product(
    name: "Summer Bash",
    price: "3.50",
    color: Colors.blue.shade200,
    imagePath: "assets/images/donut3.jpg", 
    category: "donut",
  ),
  Product(
    name: "Strawberry Kiss",
    price: "4.00",
    color: const Color.fromARGB(255, 188, 32, 144),
    imagePath: "assets/images/donut4.jpg", 
    category: "donut",
  ),
  Product(
    name: "Ghost Glazed",
    price: "4.50",
    color: Colors.blue.shade200,
    imagePath: "assets/images/donut5.jpg", 
    category: "donut",
  ),
  Product(
    name: "Karamel Swirl",
    price: "5.00",
    color: const Color.fromARGB(255, 92, 52, 8),
    imagePath: "assets/images/donut6.jpg", 
    category: "donut",
  ),
  // --- BURGERS ---
  Product(
    name: "Chicken Burger",
    price: "8.00",
    color: Colors.orange.shade300,
    imagePath: "assets/images/burger1.jpg",
    category: "burger",
  ),
  Product(
    name: "Premium Rib Sandwich",
    price: "9.00",
    color: const Color.fromARGB(255, 199, 180, 41),
    imagePath: "assets/images/burger2.jpg",
    category: "burger",
  ),
  Product(
    name: "Special Cheeseburger",
    price: "7.00",
    color: const Color.fromARGB(255, 221, 212, 46),
    imagePath: "assets/images/burger3.jpg",
    category: "burger",
  ),
  Product(
    name: "Classic Burger (Combo)",
    price: "8.00",
    color: Colors.orange.shade300,
    imagePath: "assets/images/burger4.jpg",
    category: "burger",
  ),
  Product(
    name: "Grass-Fed Burger",
    price: "9.50",
    color: const Color.fromARGB(255, 54, 169, 19),
    imagePath: "assets/images/burger5.jpg",
    category: "burger",
  ),
  Product(
    name: "Twice the Meat",
    price: "12.50",
    color: const Color.fromARGB(255, 189, 14, 43),
    imagePath: "assets/images/burger6.jpg",
    category: "burger",
  ),
  // --- PIZZAS ---
  Product(
    name: "Three ingredients Pizza",
    price: "12.00",
    color: const Color.fromARGB(255, 49, 140, 193),
    imagePath: "assets/images/pizza1.jpg",
    category: "pizza",
  ),
    Product(
    name: "Deluxe Pizza",
    price: "13.50",
    color: Colors.red.shade300,
    imagePath: "assets/images/pizza2.jpg",
    category: "pizza",
  ),
    Product(
    name: "Special Veggie",
    price: "12.50",
    color: const Color.fromARGB(255, 125, 209, 117),
    imagePath: "assets/images/pizza3.jpg",
    category: "pizza",
  ),
    Product(
    name: "Pepperoni Feast",
    price: "12.00",
    color: const Color.fromARGB(255, 132, 6, 6),
    imagePath: "assets/images/pizza4.jpg",
    category: "pizza",
  ),
    Product(
    name: "Wombo Combo",
    price: "13.50",
    color: const Color.fromARGB(255, 220, 137, 137),
    imagePath: "assets/images/pizza5.jpg",
    category: "pizza",
  ),
    Product(
    name: "Double Rounds",
    price: "20.00",
    color: const Color.fromARGB(255, 175, 162, 15),
    imagePath: "assets/images/pizza6.jpg",
    category: "pizza",
  ),
  // --- ICECREAM ---
  Product(
    name: "Classic Choco",
    price: "3.00",
    color: const Color.fromARGB(255, 115, 70, 3),
    imagePath: "assets/images/icecream1.jpg",
    category: "icecream",
  ),
  Product(
    name: "Pistaccio Bomb",
    price: "2.50",
    color: const Color.fromARGB(255, 128, 185, 15),
    imagePath: "assets/images/icecream2.jpg",
    category: "icecream",
  ),
  Product(
    name: "Bubblegum Pop",
    price: "3.50",
    color: const Color.fromARGB(255, 37, 202, 220),
    imagePath: "assets/images/icecream3.jpg",
    category: "icecream",
  ),
  Product(
    name: "Grimmace Grape",
    price: "4.00",
    color: const Color.fromARGB(255, 167, 27, 188),
    imagePath: "assets/images/icecream4.jpg",
    category: "icecream",
  ),
  Product(
    name: "Fruity Rainbow",
    price: "4.00",
    color: const Color.fromARGB(255, 223, 216, 14),
    imagePath: "assets/images/icecream5.jpg",
    category: "icecream",
  ),
  Product(
    name: "Vanilla Classic",
    price: "3.00",
    color: const Color.fromARGB(255, 93, 214, 12),
    imagePath: "assets/images/icecream6.jpg",
    category: "icecream",
  ),
  // --- DRINKS ---
  Product(
    name: "Coca Cola",
    price: "1.00",
    color: const Color.fromARGB(255, 106, 35, 9),
    imagePath: "assets/images/soda1.jpg",
    category: "drinks",
  ),
  Product(
    name: "Diet Coke",
    price: "1.00",
    color: const Color.fromARGB(255, 13, 64, 175),
    imagePath: "assets/images/soda2.jpg",
    category: "drinks",
  ),
  Product(
    name: "Sprite",
    price: "1.20",
    color: const Color.fromARGB(255, 25, 199, 6),
    imagePath: "assets/images/soda3.jpg",
    category: "drinks",
  ),
  Product(
    name: "Latte",
    price: "3.50",
    color: const Color.fromARGB(255, 156, 89, 12),
    imagePath: "assets/images/soda4.jpg",
    category: "drinks",
  ),
  Product(
    name: "Milkshake",
    price: "3.00",
    color: const Color.fromARGB(255, 202, 87, 163),
    imagePath: "assets/images/soda5.jpg",
    category: "drinks",
  ),
  Product(
    name: "Water",
    price: "0.50",
    color: Colors.brown.shade300,
    imagePath: "assets/images/soda6.jpg",
    category: "drinks",
  ),
];